### ISSUE TITLE
Contribution ? :3

### ISSUE THREAD

**Issue by TadavomnisT** [Sugaryyyy/FemboyOS#1]
Hi!
This is going to be hell of a distro mate! Any chance of getting involved in (or with!) the project ?!
UwU It would be a pleasure to Contribute :3

**Comment by TadavomnisT** [comment]
Hi again @Sugaryyyy  *-*

Sorry for being late, I was bussy... awhm sry busy for the past few days!
You mentioned that you're "stuck with the login broken" earlier , so I decided to take a look under the hood of what you did so far. Before that I wanned to ThanQ for creating contribution guides and auto scripts for building the project :+1: 

There were some... problems with `prepare.sh` and other scripts in my scenario ... That's why I made some changes and opened a PR #2  , here is an explanation of changes :

`prepare.sh`:

```diff
- echo "Testing $LFS and $DIST_ROOT variables, if you don't have them set,"
- echo "LFS is: '(path to FemboyOS)/build_env/build_root' (eg. /basia/FemboyOS//build_env/build_root/), and $DIST_ROOT is (path to FemboyOS) (eg. /basia/FemboyOS/)"
+ echo "Testing \$LFS and \$DIST_ROOT variables, if you don't have them set,"
+ echo "\n\$LFS is: '(path to FemboyOS)/build_env/build_root' (eg. /basia/FemboyOS/build_env/build_root/), and \$DIST_ROOT is (path to FemboyOS) (eg. /basia/FemboyOS/)"

+ if [ -z ${LFS+x} ]; then
+ echo "[*]\$LFS is not defined or NULL";
+ exit -1
+ fi
+ if [ -z ${DIST_ROOT+x} ]; then
+ echo "[*]\$DIST_ROOT is not defined or NULL";
+ exit -1
+ fi
```
The $DollarSign is special char, so it needs to be escaped in strings, otherwise it represents a variable.
and I added some extra var checkers if you don't mind *-*   

```diff
- mkdir -pv $LFS/{bin,etc,lib,sbin,usr,var,lib64,tools}

+ mkdir -pv $LFS/bin
+ mkdir -pv $LFS/etc
+ mkdir -pv $LFS/lib
+ mkdir -pv $LFS/sbin
+ mkdir -pv $LFS/usr
+ mkdir -pv $LFS/var
+ mkdir -pv $LFS/lib64
+ mkdir -pv $LFS/tools
```
From what I found out, The bash encapsulates parameters as strings , so if you execute:
```shell
mkdir -pv $LFS/{bin,etc,lib,sbin,usr,var,lib64,tools}
```
as a single command in terminal , It works perfectly alright , But in bash It creates a single directory named `{bin,etc,lib,sbin,usr,var,lib64,tools}` which is insane! So there are several ways to prevent that, but making them one after another is the simplest way.

```diff
- groupadd distbuild
- useradd -s /bin/bash -g distbuild -m -k /dev/null distbuild
- passwd distbuild
- chown -v distbuild $LFS/{usr,lib,var,etc,bin,sbin,tools,lib64,sources}
+ sudo groupadd distbuild
+ sudo useradd -s /bin/bash -g distbuild -m -k /dev/null distbuild
+ sudo passwd distbuild
+ sudo chown -v distbuild $LFS/usr
+ sudo chown -v distbuild $LFS/lib
+ sudo chown -v distbuild $LFS/var
+ sudo chown -v distbuild $LFS/etc
+ sudo chown -v distbuild $LFS/bin
+ sudo chown -v distbuild $LFS/sbin
+ sudo chown -v distbuild $LFS/tools
+ sudo chown -v distbuild $LFS/lib64
+ sudo chown -v distbuild $LFS/sources
```
As far as I know, calling commands like `groupadd` or `useradd` or `passwd` or even `chown`  requires root access,... well tbh It does in my distro, dunno about others! 
So, I think it's safe to add `sudo`  ...
and the same thing as `mkdir` goes for `chown` when dealing with several directories... So I put it in several commands. 
_____________________

Did some changes to `create.sh`  too :
```diff
+ if [ -z ${LFS+x} ]; then
+ echo "[*]\$LFS is not defined or NULL";
+ exit -1
+ fi
+ if [ -z ${DIST_ROOT+x} ]; then
+ echo "[*]\$DIST_ROOT is not defined or NULL";
+ exit -1
+ fi
```
Just a simple checker, not a big deal...
_____________________

So after all these , when I run `create.sh` I get this error:
```
tar: binutils-2.39: Cannot mkdir: Permission denied
```
I thought I should add distbuild as a sudoer, But that was wrong, distbuild must NOT be a sudoer at all bcuz that'll defeat the whole purpose... I Think we created this user to prevent super damages to system like what sudoers do!!!

So the next thing that comes to my mind is that I should've added `/build_env` dir into ownership of distbuild or sth? I'm stuck here...
I decided to ask you, before going any further.

And It would be a real pleasure for me to contributor here ...
Thanks in advance <3

**Comment by Sugaryyyy** [comment]
Henlo, I think distbuild doesn't have permission to the directory sources/ in build_root.
Try checking the permissions of the build_root folder. 
:3

**Comment by Sugaryyyy** [comment]
Good news,
I found the issue with the login!
I missed a very important step of linking /bin to /usr/bin.
:3 :3 :3

**Comment by TadavomnisT** [comment]
Hiiiii @Sugaryyyy !
Congrats mate:3
I noticed and been tying to tell you but, it's a bit hard with no internet!

> Henlo, I think distbuild doesn't have permission to the directory sources/ in build_root.
> Try checking the permissions of the build_root folder.
> :3

Yes that was the case, Thank you.

____________________________
Anyways, I'm trying to cross-compile the project on different architecutres, but ran into some problems... Trying to fix em, but I call on an Issue if I couldn't fix^_^

Keep up with the good work :1st_place_medal:
